### ISSUE TITLE
[SUGGESTION] Add a version without docker 

### ISSUE THREAD

**Issue by ENC4YP7ED** [overextended/OxBot#3]
I use windows server 2022 as opperatingsystem for my server and wanted to run them but windows has no docker so I wanted to ask if you could create a version that works on normal desktop Windows

**Comment by LukeWasTakenn** [comment]
Windows does have docker and the bot only exists for our discord server in mind and just so happens to be open sourced, it's not receiving any kind of maintenance and support for anything other than what our needs are.
